declare const flags: { code: string; emoji: string }[];
export default [
    { code: "US", name: "United States", emoji: "🇺🇸" },
    { code: "GB", name: "United Kingdom", emoji: "🇬🇧" },
    { code: "CA", name: "Canada", emoji: "🇨🇦" },
    { code: "FR", name: "France", emoji: "🇫🇷" },
    { code: "DE", name: "Germany", emoji: "🇩🇪" },
    { code: "IT", name: "Italy", emoji: "🇮🇹" },
    { code: "ES", name: "Spain", emoji: "🇪🇸" },
    { code: "RU", name: "Russia", emoji: "🇷🇺" },
    { code: "CN", name: "China", emoji: "🇨🇳" },
    { code: "JP", name: "Japan", emoji: "🇯🇵" },
    { code: "KR", name: "South Korea", emoji: "🇰🇷" },
    { code: "IN", name: "India", emoji: "🇮🇳" },
    { code: "BR", name: "Brazil", emoji: "🇧🇷" },
    { code: "MX", name: "Mexico", emoji: "🇲🇽" },
    { code: "AU", name: "Australia", emoji: "🇦🇺" },
    { code: "ZA", name: "South Africa", emoji: "🇿🇦" },
    { code: "NG", name: "Nigeria", emoji: "🇳🇬" },
    { code: "EG", name: "Egypt", emoji: "🇪🇬" },
    { code: "TR", name: "Turkey", emoji: "🇹🇷" },
    { code: "AR", name: "Argentina", emoji: "🇦🇷" },
    { code: "UY", name: "Uruguay", emoji: "🇺🇾" }, 
    { code: "SE", name: "Sweden", emoji: "🇸🇪" },
    { code: "NO", name: "Norway", emoji: "🇳🇴" },
    { code: "FI", name: "Finland", emoji: "🇫🇮" },
    { code: "DK", name: "Denmark", emoji: "🇩🇰" },
    { code: "PL", name: "Poland", emoji: "🇵🇱" },
    { code: "NL", name: "Netherlands", emoji: "🇳🇱" },
    { code: "BE", name: "Belgium", emoji: "🇧🇪" },
    { code: "CH", name: "Switzerland", emoji: "🇨🇭" },
    { code: "AT", name: "Austria", emoji: "🇦🇹" },
    { code: "GR", name: "Greece", emoji: "🇬🇷" },
    { code: "PT", name: "Portugal", emoji: "🇵🇹" },
    { code: "IE", name: "Ireland", emoji: "🇮🇪" },
    { code: "IL", name: "Israel", emoji: "🇮🇱" },
    { code: "SA", name: "Saudi Arabia", emoji: "🇸🇦" },
    { code: "AE", name: "United Arab Emirates", emoji: "🇦🇪" },
    { code: "SG", name: "Singapore", emoji: "🇸🇬" },
    { code: "TH", name: "Thailand", emoji: "🇹🇭" },
    { code: "ID", name: "Indonesia", emoji: "🇮🇩" },
    { code: "MY", name: "Malaysia", emoji: "🇲🇾" },
    { code: "PH", name: "Philippines", emoji: "🇵🇭" },
    { code: "VN", name: "Vietnam", emoji: "🇻🇳" },
    { code: "NZ", name: "New Zealand", emoji: "🇳🇿" },
    { code: "CL", name: "Chile", emoji: "🇨🇱" },
    { code: "CO", name: "Colombia", emoji: "🇨🇴" },
    { code: "PE", name: "Peru", emoji: "🇵🇪" },
    { code: "PK", name: "Pakistan", emoji: "🇵🇰" },
    { code: "BD", name: "Bangladesh", emoji: "🇧🇩" },
    { code: "UA", name: "Ukraine", emoji: "🇺🇦" },
    { code: "RO", name: "Romania", emoji: "🇷🇴" },
    { code: "HU", name: "Hungary", emoji: "🇭🇺" },
    { code: "CZ", name: "Czechia", emoji: "🇨🇿" },
    { code: "SK", name: "Slovakia", emoji: "🇸🇰" },
    { code: "BG", name: "Bulgaria", emoji: "🇧🇬" },
    { code: "HR", name: "Croatia", emoji: "🇭🇷" },
    { code: "RS", name: "Serbia", emoji: "🇷🇸" },
    { code: "SI", name: "Slovenia", emoji: "🇸🇮" },
    { code: "LT", name: "Lithuania", emoji: "🇱🇹" },
    { code: "LV", name: "Latvia", emoji: "🇱🇻" },
    { code: "EE", name: "Estonia", emoji: "🇪🇪" },
    { code: "LU", name: "Luxembourg", emoji: "🇱🇺" },
    { code: "IS", name: "Iceland", emoji: "🇮🇸" },
    { code: "MT", name: "Malta", emoji: "🇲🇹" },
    { code: "CY", name: "Cyprus", emoji: "🇨🇾" },
    { code: "QA", name: "Qatar", emoji: "🇶🇦" },
    { code: "KW", name: "Kuwait", emoji: "🇰🇼" },
    { code: "OM", name: "Oman", emoji: "🇴🇲" },
    { code: "BH", name: "Bahrain", emoji: "🇧🇭" },
    { code: "JO", name: "Jordan", emoji: "🇯🇴" },
    { code: "LB", name: "Lebanon", emoji: "🇱🇧" },
    { code: "MA", name: "Morocco", emoji: "🇲🇦" },
    { code: "DZ", name: "Algeria", emoji: "🇩🇿" },
    { code: "TN", name: "Tunisia", emoji: "🇹🇳" },
    { code: "KE", name: "Kenya", emoji: "🇰🇪" },
    { code: "GH", name: "Ghana", emoji: "🇬🇭" },
    { code: "ET", name: "Ethiopia", emoji: "🇪🇹" },
    { code: "UG", name: "Uganda", emoji: "🇺🇬" },
    { code: "TZ", name: "Tanzania", emoji: "🇹🇿" },
    { code: "SD", name: "Sudan", emoji: "🇸🇩" },
    { code: "SN", name: "Senegal", emoji: "🇸🇳" },
    { code: "CM", name: "Cameroon", emoji: "🇨🇲" },
    { code: "CI", name: "Ivory Coast", emoji: "🇨🇮" },
    { code: "AO", name: "Angola", emoji: "🇦🇴" },
    { code: "ZW", name: "Zimbabwe", emoji: "🇿🇼" },
    { code: "MZ", name: "Mozambique", emoji: "🇲🇿" },
    { code: "MG", name: "Madagascar", emoji: "🇲🇬" },
    { code: "CD", name: "Congo (DRC)", emoji: "🇨🇩" },
    { code: "CG", name: "Congo (Republic)", emoji: "🇨🇬" },
    { code: "UG", name: "Uganda", emoji: "🇺🇬" },
    { code: "ZM", name: "Zambia", emoji: "🇿🇲" },
    { code: "NA", name: "Namibia", emoji: "🇳🇦" },
    { code: "BW", name: "Botswana", emoji: "🇧🇼" },
    { code: "MW", name: "Malawi", emoji: "🇲🇼" },
    { code: "LS", name: "Lesotho", emoji: "🇱🇸" },
    { code: "SZ", name: "Eswatini", emoji: "🇸🇿" },
    { code: "GM", name: "Gambia", emoji: "🇬🇲" },
    { code: "SL", name: "Sierra Leone", emoji: "🇸🇱" },
    { code: "LR", name: "Liberia", emoji: "🇱🇷" },
    { code: "MR", name: "Mauritania", emoji: "🇲🇷" },
    { code: "NE", name: "Niger", emoji: "🇳🇪" },
    { code: "ML", name: "Mali", emoji: "🇲🇱" },
    { code: "BF", name: "Burkina Faso", emoji: "🇧🇫" },
    { code: "BJ", name: "Benin", emoji: "🇧🇯" },
    { code: "TG", name: "Togo", emoji: "🇹🇬" },
    { code: "RW", name: "Rwanda", emoji: "🇷🇼" },
    { code: "BI", name: "Burundi", emoji: "🇧🇮" },
    { code: "SO", name: "Somalia", emoji: "🇸🇴" },
    { code: "DJ", name: "Djibouti", emoji: "🇩🇯" },
    { code: "ER", name: "Eritrea", emoji: "🇪🇷" },
    { code: "CF", name: "Central African Republic", emoji: "🇨🇫" },
    { code: "GA", name: "Gabon", emoji: "🇬🇦" },
    { code: "GQ", name: "Equatorial Guinea", emoji: "🇬🇶" },
    { code: "ST", name: "Sao Tome and Principe", emoji: "🇸🇹" },
    { code: "CV", name: "Cape Verde", emoji: "🇨🇻" },
    { code: "KM", name: "Comoros", emoji: "🇰🇲" },
    { code: "SC", name: "Seychelles", emoji: "🇸🇨" },
    { code: "MU", name: "Mauritius", emoji: "🇲🇺" },
    { code: "SZ", name: "Eswatini", emoji: "🇸🇿" },
    { code: "FJ", name: "Fiji", emoji: "🇫🇯" },
    { code: "PG", name: "Papua New Guinea", emoji: "🇵🇬" },
    { code: "SB", name: "Solomon Islands", emoji: "🇸🇧" },
    { code: "VU", name: "Vanuatu", emoji: "🇻🇺" },
    { code: "AS", name: "Samoa", emoji: "🇼🇸" },
    { code: "TO", name: "Tonga", emoji: "🇹🇴" },
    { code: "TV", name: "Tuvalu", emoji: "🇹🇻" },
    { code: "KI", name: "Kiribati", emoji: "🇰🇮" },
    { code: "NR", name: "Nauru", emoji: "🇳🇷" },
    { code: "MH", name: "Marshall Islands", emoji: "🇲🇭" },
    { code: "FM", name: "Micronesia", emoji: "🇫🇲" },
    { code: "PW", name: "Palau", emoji: "🇵🇼" },
    { code: "TL", name: "Timor-Leste", emoji: "🇹🇱" },
    { code: "BN", name: "Brunei", emoji: "🇧🇳" },
    { code: "LA", name: "Laos", emoji: "🇱🇦" },
    { code: "KH", name: "Cambodia", emoji: "🇰🇭" },
    { code: "MM", name: "Myanmar", emoji: "🇲🇲" },
    { code: "MN", name: "Mongolia", emoji: "🇲🇳" },
    { code: "KZ", name: "Kazakhstan", emoji: "🇰🇿" },
    { code: "UZ", name: "Uzbekistan", emoji: "🇺🇿" },
    { code: "TM", name: "Turkmenistan", emoji: "🇹🇲" },
    { code: "KG", name: "Kyrgyzstan", emoji: "🇰🇬" },
    { code: "TJ", name: "Tajikistan", emoji: "🇹🇯" },
    { code: "AF", name: "Afghanistan", emoji: "🇦🇫" },
    { code: "IR", name: "Iran", emoji: "🇮🇷" },
    { code: "IQ", name: "Iraq", emoji: "🇮🇶" },
    { code: "SY", name: "Syria", emoji: "🇸🇾" },
    { code: "YE", name: "Yemen", emoji: "🇾🇪" },
    { code: "PS", name: "Palestine", emoji: "🇵🇸" },
    { code: "AZ", name: "Azerbaijan", emoji: "🇦🇿" },
    { code: "GE", name: "Georgia", emoji: "🇬🇪" },
    { code: "AM", name: "Armenia", emoji: "🇦🇲" },
    { code: "MD", name: "Moldova", emoji: "🇲🇩" },
    { code: "BY", name: "Belarus", emoji: "🇧🇾" },
    { code: "MC", name: "Monaco", emoji: "🇲🇨" },
    { code: "LI", name: "Liechtenstein", emoji: "🇱🇮" },
    { code: "SM", name: "San Marino", emoji: "🇸🇲" },
    { code: "VA", name: "Vatican City", emoji: "🇻🇦" },
    { code: "AD", name: "Andorra", emoji: "🇦🇩" },
    { code: "AL", name: "Albania", emoji: "🇦🇱" },
    { code: "MK", name: "North Macedonia", emoji: "🇲🇰" },
    { code: "ME", name: "Montenegro", emoji: "🇲🇪" },
    { code: "BA", name: "Bosnia and Herzegovina", emoji: "🇧🇦" },
    { code: "XK", name: "Kosovo", emoji: "🇽🇰" }
];
